CLI 1
ekiuled/cli pull request #1
Opened 2021-02-20 12:28 UTC by ekiuled

2021-02-25 01:14 UTC, aleksZubakov requested changes
В целом, аккуратно и хорошо. Оставил какие-то замечания. 

Попозже еще приду что-нибудь поломать, когда доберусь нормально потестировать, пока исправляйте что есть

2021-02-25 01:14 UTC, ottergottaott commented on cli/commands.py
> +    def catFile(self,
Я тут обнаружил, что в стандартной библиотеке python тоже есть имена функций в `camelCase`, но Вы же не пишете стандартную библиотеку python _<s>(Вы же нормальный человек)</s>_, используйте `snake_case`

2021-02-25 01:14 UTC, ottergottaott commented on cli/commands.py
> +                 inp: TextIO,
Идея использовать потоки -- хорошая, но, думаю, это и так по реализации команд понятно

2021-02-25 01:14 UTC, ottergottaott commented on cli/commands.py
> +            ret = subprocess.call([self.command, *args],
А чего не 
```python
return subprocess ...
```

Если Вы завели переменную, потому что хотели произвольный int превратить в `ExitCode`, то Вы забыли это сделать :)

2021-02-25 01:14 UTC, ottergottaott commented on cli/interpreter.py
> +environment = dict()
Мне не нравится, что эта штука в глобальном пространстве имен болтается. Кажется, что ей не место там

Больше похоже на параметр функции `run`, на самом деле. Понимаю, что с замыканием удобно, но подумайте, мб, можно как-то по-другому

2021-02-25 01:14 UTC, aleksZubakov commented on cli/interpreter.py
> +    for command, args in pipeline[1:-1]:
По моему (весьма субъективному) опыту, если одну из итераций приходится перед циклом делать, то что-то не так с циклом и это обычно исправляется небольшими изменениями (чаще всего изменение состояния в другом месте).

Попробуйте свернуть это дело, если не получится, пинайте -- обсудим

2021-02-25 01:14 UTC, aleksZubakov commented on cli/parser.py
> +        value = variable_expansion(match.group(2), environment)
Я же поломаю это, ну( 
Почему-то игнорируете, что кавычки одинарные бывают,  и в них хорошо бы не делать подстановки:
```bash
'asd$a'
```
Чтобы у меня не получалось ничего ломать, подумайте сразу о всяких сложно сочиненных случаях по типу `b="a'$c'e"` и `b='a"$c"e'`

2021-02-25 01:14 UTC, aleksZubakov commented on cli/parser.py
> +    return [name_args(command, environment) for command in commands]
Кстати, как сайд-эффект исправления цикла выше: если бы снаружи никто не использовал индексирование, тут можно было бы не список возвращать, а прям не стесняясь `parse` генератором сделать. Памяти меньше, операций столько же, оверхед незначительный в данном случае

2021-02-25 01:14 UTC, aleksZubakov commented on cli/parser.py
> +        if match[2]:
Вот эти `match[2]` тоже бы как-то заименовать, а то непонятно

2021-02-26 12:00 UTC, ekiuled commented on cli/commands.py
> +                 inp: TextIO,
Это к тому, что тут не нужно аннотирование?

2021-02-26 12:00 UTC, ekiuled commented on cli/interpreter.py
> +environment = dict()
Можно сделать интерпретатор классом и спрятать `environment` в него :)

2021-02-26 12:00 UTC, ekiuled commented on cli/interpreter.py
> +    for command, args in pipeline[1:-1]:
Я здесь так сделала, потому что для первой и последней итерации используются `sys.stdin` и `sys.stdout`, которые не нужно закрывать. Как унифицированно делать до два `with open`, то один — я что-то не придумала.

2021-02-27 16:25 UTC, aleksZubakov commented on cli/commands.py
> +                 inp: TextIO,
Не, это я просто одобрил хорошую идею)

2021-03-12 00:16 UTC, aleksZubakov commented on cli/interpreter.py
> +    for command, args in pipeline[1:-1]:
Ладно, чего-то я тоже ничего не придумал, оставим как есть :)

2021-03-12 00:16 UTC, aleksZubakov commented
> Попозже еще приду что-нибудь поломать, когда доберусь нормально потестировать, пока исправляйте что есть

Вроде, ничего дополнительно не сломал. Цветастый repl красиво выглядит! Думаю, что готов засчитывать

2021-03-17 22:09 UTC, ekiuled commented
> > Попозже еще приду что-нибудь поломать, когда доберусь нормально потестировать, пока исправляйте что есть
> 
> Вроде, ничего дополнительно не сломал. Цветастый repl красиво выглядит! Думаю, что готов засчитывать

Можно мёржить эту ветку в мастер? Я ещё в соседний PR дописала.

2021-03-17 22:52 UTC, aleksZubakov commented
Ага

2021-03-18 16:11 UTC, merged